spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(idwa42E+EQqUMesWBABP4Iac2O/32NEJPXFerFSjb73xk05NkBWLrklB2ux9ck0m9K3ETuRd0jReosqsaT6nB+PGiqrx4bTJQmz0iMycB/reI/bRfbPkwQ==)
            client-secret: ENC(vhjYbhQQ+XzHQXR2N41p0gsv3FzD3GGJE+W73+8B2P7L3LEODMsl+rlUFzgBfP5+)
            scope:
              - profile
              - email

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}