version: '3'

services:
  local-db:
    container_name: local-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: boilerplate
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    restart: always
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - boilerplate-local

  local-app:
    container_name: local-app
    environment:
      - SPRING_PROFILES_ACTIVE=local,core,oauth
#      - jasypt.encryptor.password=
      - TZ=Asia/Seoul
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - local-db
    networks:
      - boilerplate-local

networks:
  boilerplate-local:
    driver: bridge