version: '3'

services:
  local-db:
    container_name: local-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: boilerplate
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    restart: always
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - boilerplate-local

  local-app:
    container_name: local-app
    environment:
      - SPRING_PROFILES_ACTIVE=local,core,oauth
#      - jasypt.encryptor.password= TODO 사용할떄 변경할것
      - TZ=Asia/Seoul
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - local-db
    networks:
      - boilerplate-local

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9091:9091
    restart: unless-stopped
    volumes:
      - ../prometheus:/etc/prometheus
      - prom_data:/prometheus
    depends_on:
      - local-app
    networks:
      - boilerplate-local

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ../grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - local-app
    networks:
      - boilerplate-local
volumes:
  prom_data:

networks:
  boilerplate-local:
    driver: bridge