spring.profiles.active: local

spring:
  profiles:
    include:
      - core
      - oauth
#  특정 profile을 사용했을 떄 여러 개의 profile을 참조할 수 있음.
#    group:
#      local: logging-console
#      dev: logging-file-config
#  config:
#    import:
#      - application-core.yml
  # 수동 & 자동 빈 이름 충돌 방지 설정
  main:
    allow-bean-definition-overriding: true

# remove to jSession
server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
  tomcat:
    mbeanregistry:
      enabled: true

# https://hudi.blog/spring-boot-actuator-prometheus-grafana-set-up/
management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      # 각 health 정보를 상세하게 또는 간단하게 표현할지에 대한 속성을 선언한다.
      #      show-details: always
      show-components: always

